global:
  smtp_smarthost: "localhost:587"
  smtp_from: "alerts@isp.local"

route:
  receiver: "telegram"
  group_by: ["alertname", "severity"]
  group_wait: 10s
  group_interval: 10s
  repeat_interval: 1h

receivers:
  - name: "telegram"
    telegram_configs:
      - api_url: "https://api.telegram.org"
        bot_token: "TOKEN_ID"
        chat_id: -1
        message: |
          {{ range .Alerts }}
          Alert: {{ .Annotations.summary }}
          Description: {{ .Annotations.description }}
          Severity: {{ .Labels.severity }}
          {{ end }}
